### ISSUE TITLE
probe-domain TypeError in response data (warnings)

### ISSUE THREAD

**Issue by dspruell** [dspruell/resolve-hosts#6]
- Python 3.10.12
- resolve-hosts 0.2.0

```
$ probe-domain solntsepek.ru
Traceback (most recent call last):
  File "/opt/shared/bin/probe-domain", line 8, in <module>
    sys.exit(probe_domain())
             ^^^^^^^^^^^^^^
  File "/opt/shared/pipx/venvs/resolve-hosts/lib/python3.11/site-packages/resolve_hosts/cli.py", line 130, in probe_domain
    domain_reg = get_domain_summary(domain)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/shared/pipx/venvs/resolve-hosts/lib/python3.11/site-packages/resolve_hosts/whois.py", line 17, in get_domain_summary
    "error in domain lookup: %s", "\n".join(resp_data["warnings"])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, list found
```

**Comment by dspruell** [comment]
Closed with #7.
